name: Wöchentliche Cypress Tests

on:
  schedule:
    - cron: '0 8 * * 1' # Jeden Montag um 8 Uhr UTC

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Verwendung von Node.js Version 16

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --headless
